/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_chen_cloud_cloud_game_mgr */

#ifndef _Included_com_chen_cloud_cloud_game_mgr
#define _Included_com_chen_cloud_cloud_game_mgr
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_chen_cloud_cloud_game_mgr
 * Method:    nativeMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_chen_cloud_cloud_1game_1mgr_nativeMethod
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
